# GTK
# export GTK_USE_PORTAL=1

# QT5
export QT_QPA_PLATFORMTHEME=qt5ct

# EDITOR
export VISUAL=nvim
export EDITOR=nvim

# COMPOSER
export PATH="$HOME/.config/composer/vendor/bin:$PATH"

# RUBY
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$GEM_HOME/bin:$PATH"

# RUST
export PATH="$HOME/.cargo/bin:$PATH"

# LOCAL BIN
export PATH="$HOME/.local/bin:$PATH"

# ANDROID DEV
export GRADLE_USER_HOME="/mnt/DATA_III/Android-Studio/.gradle"
#export STUDIO_JDK=/usr/lib/jvm/default
export ANDROID_HOME="/mnt/DATA_III/Android-Studio/Linux/SDK"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH"
export ADB_MDNS_OPENSCREEN=1

# JAVA
export AWT_TOOLKIT=MToolkit
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dsun.java2d.opengl-true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
