#!/bin/env bash

{
    case $1 in
        "--network")
            # using connman
            # export ROFI_COMMAND="rofi -dmenu -theme $HOME/.config/rofi/network.rasi
            # rofi-connman ;;

            # using Network Manager
            networkmanager_dmenu -theme "$HOME"/.config/rofi/network.rasi ;;
        "--bluetooth") blueman-manager ;;
            # "--battery") xfce4-power-manager-settings ;;
        "--volume") pavucontrol ;;
        "--taskmanager") gnome-system-monitor ;;
        "--terminal") urxvtc ;;
        *) echo "error" ;;
    esac
}
