#!/bin/env bash

level() {
    BAT=$(find /sys/class/power_supply/BAT?)
    cat "$BAT"/capacity
}
state() {
    BAT=$(find /sys/class/power_supply/BAT?)
    cat "$BAT"/status
}
icon() {
    LEVEL=$(level)
    STATS=$(state)

    if [ "$STATS" = "Charging" ]; then
        if [ "$LEVEL" -ge "95" ]; then
            echo "assets/icons/battery-empty-charging.png"
        elif [ "$LEVEL" -ge "50" ]; then
            echo "assets/icons/battery-empty-charging.png"
        elif [ "$LEVEL" -ge "20" ]; then
            echo "assets/icons/battery-empty-charging.png"
        else
            echo "assets/icons/battery-empty-charging.png"
        fi
    else
        if [ "$LEVEL" -ge "95" ]; then
            echo "assets/icons/battery-full.png"
        elif [ "$LEVEL" -ge "50" ]; then
            echo "assets/icons/battery-medium.png"
        elif [ "$LEVEL" -ge "20" ]; then
            echo "assets/icons/battery-low.png"
        else
            echo "assets/icons/battery-empty.png"
        fi
    fi
}

{
    case "$1" in
        "--level") level ;;
        "--state") state ;;
        "--icon") icon ;;
        *) "error" ;;
    esac
}
