#!/bin/sh

# modified from = https://gist.github.com/dagelf/ab2bad26ce96fa8d79b0834cd8cab549

# get active interface
INTERFACE=$(ip addr | awk '/state UP/ {print $2}' | sed 's/.$//' | head -n1 | awk '{print $1}')
TETHER=$(ip addr | awk '/usb0:/ {print $2}' | sed 's/.$//')
SLEEP=1

# check usb tethering
if [ -n "$TETHER"  ]; then
    INTERFACE=$TETHER
fi

# fallback if active inteface not found
if [ -z "$INTERFACE" ] && [ -z "$TETHER" ]; then
    INTERFACE="wlan0"
fi

LINE=$(grep "$INTERFACE" /proc/net/dev 2> /dev/null | sed s/.*://)
RECEIVED1=$(echo "$LINE" | awk '{print $1}')
TRANSMITTED1=$(echo "$LINE" | awk '{print $9}')
TOTAL=$((RECEIVED1 + TRANSMITTED1))

sleep $SLEEP

LINE=$(grep "$INTERFACE" /proc/net/dev 2> /dev/null | sed s/.*://)
RECEIVED2=$(echo "$LINE" | awk '{print $1}')
TRANSMITTED2=$(echo "$LINE" | awk '{print $9}')

SPEED=$(((RECEIVED2 + TRANSMITTED2 - TOTAL)/SLEEP))
DOWNLOAD=$(((RECEIVED2 - RECEIVED1)/SLEEP))
UPLOAD=$(((TRANSMITTED2 - TRANSMITTED1)/SLEEP))

download(){
    echo "$((DOWNLOAD/1025))";
}

upload(){
    echo "$((UPLOAD/1024))";
}

total(){
    echo "$((SPEED/1024))";
}

{
    case $1 in
        "--download") download ;;
        "--upload") upload ;;
            # "--total") total ;;
        "--interface") echo "$INTERFACE" ;;
    esac
}
