#!/bin/bash

WIFI=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)
SSID=$(iwgetid | awk -F '"' '{ print $2 }')

icon() {
    if [[ $WIFI != "" ]]; then
        if [[ "$WIFI" -ge "75" ]]; then
            echo "assets/icons/wifi-full.png"
        elif [[ "$WIFI" -ge "50" ]]; then
            echo "assets/icons/wifi-medium.png"
        elif [[ "$WIFI" -ge "25" ]]; then
            echo "assets/icons/wifi-low.png"
        elif [[ "$WIFI" -ge "0" ]]; then
            echo "assets/icons/wifi-weak.png"
        fi
    else
        echo "assets/icons/wifi-off.png"
    fi
}

state(){
    if [[  -z $SSID ]]; then
        echo "Disconnected"
    else
        echo "Connected to ${SSID}"
    fi
}

if [[ $1 = "--ssid" ]]; then
    if [[ -z $SSID ]]; then
        echo "Disconnected"
    else
        echo "${SSID}"
    fi
elif [[ $1 = "--icon" ]]; then
    icon
elif [[ $1 = "--state" ]]; then
    state
fi
