#!/bin/sh

bspc rule -a Gimp-2.10 desktop='^8' follow=on
bspc rule -a Blueman-manager state=floating
bspc rule -a Blueman-services state=floating
bspc rule -a URxvt state=floating center=true
bspc rule -a smplayer state=floating
bspc rule -a Bluetooth-sendto state=floating center=true
bspc rule -a Arandr state=floating
bspc rule -a Xarchiver state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Viewnior state=floating follow=on center=true
bspc rule -a Gpick state=floating
bspc rule -a L3afpad state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Catfish state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Yad state=floating
bspc rule -a System-config-printer.py state=floating center=true
bspc rule -a Galculator state=floating
bspc rule -a hp-toolbox state=floating
bspc rule -a xpad state=floating border=off locked=on sticky=on layer=below manage=off
bspc rule -a xdman-Main state=floating
bspc rule -a scrcpy state=floating
bspc rule -a Light-locker-settings.py state=floating center=true
bspc rule -a Wihotspot-gui state=floating center=true
bspc rule -a Cpupower-gui state=floating center=true
bspc rule -a Magnus state=floating
bspc rule -a Weston\ Compositor state=floating
bspc rule -a Xfce4-power-manager-settings state=floating center=true
bspc rule -a kdeconnect.app state=floating center=true
bspc rule -a kdeconnect.sms state=floating center=true
bspc rule -a kdeconnect.daemon state=floating center=true
bspc rule -a jamesdsp state=floating center=true
bspc rule -a Gufw.py state=floating
bspc rule -a Connman-gtk state=floating
bspc rule -a 7zfm state=floating
bspc rule -a Gcr-viewer state=floating
bspc rule -a CMST\ -\ Connman\ System\ Tray state=floating center=true rectangle=720x680+0+0
