#!/bin/env bash

WID="$1"
CLASS="$2"
INSTANCE="$3"
CONSEQUENCES="$4"
WINDOW_NAME=$(xdotool getwindowname "$WID")
WINDOW_ROLE=$(xprop -id "$WID" WM_WINDOW_ROLE | cut -d'"' -f 2)

case "$CLASS" in
    "Brave-browser")
        case "$WINDOW_ROLE" in
            "pop-up")
                echo "state=floating"
                ;;
        esac
        ;;
    "Thunar")
        case "$WINDOW_NAME" in
            "File Operation Progress"|"Confirm to replace")
                echo "state=floating"
                ;;
        esac
        ;;
    "jetbrains-studio")
        [ "$WINDOW_NAME" = "splash" ] && echo "state=floating center=true"
        ;;
esac

case "$WINDOW_NAME" in
    "Event Tester")
        echo "state=floating"
        ;;
    "btop")
        echo "state=tiled"
        ;;
    "Picture in picture"|"Picture-in-Picture")
        echo "state=floating sticky=on"
        ;;
    "Library")
        echo "state=floating"
        ;;
esac
